Add Parser, Splitter and CommandIndex
eqimd/bashgo pull request #6
Opened 2023-10-07 09:08 UTC by DenisKorotchenko

2023-10-07 18:47 UTC, eqimd requested changes

2023-10-07 18:47 UTC, eqimd commented on internal/command/splitter/gotest/command_splitter_test.go
> +	expectedArgs := make([]command.CommandArgument, 2)
почему здесь 2 аргумента, если там один аргумент 'sddsadsad asdsdasd'?

2023-10-07 18:47 UTC, eqimd commented on internal/command/splitter/gotest/command_splitter_test.go
> +	expectedArgs := make([]command.CommandArgument, 2)
здесь то же самое -- аргумент должен быть один

2023-10-07 18:47 UTC, eqimd commented on internal/command/splitter/gotest/command_splitter_test.go
> +	expectedArgs := make([]command.CommandArgument, 2)
и здесь

2023-10-07 18:47 UTC, eqimd commented on internal/command/splitter/gotest/command_splitter_test.go
> +	expectedArgs := make([]command.CommandArgument, 2)
и здесь

2023-10-07 18:47 UTC, eqimd commented on internal/pipe/parser/gotest/pipe_parser_test.go
> +func TestEcho(t *testing.T) {
нужно более репрезентативное название -- мы же не команду echo тестируем. лучше назвать просто `TestPipeParserSimple`

2023-10-07 18:47 UTC, eqimd commented on internal/command/splitter/command_splitter_impl.go
> +	var waitFor = rune(' ')
сделай здесь и ниже просто байт, думаю можем не запариваться с рунами

2023-10-07 18:47 UTC, eqimd commented on internal/command/splitter/command_splitter_impl.go
> +	tryEnvSplit := strings.Split(commandWord, "=")
тут работает, если вокруг "=" пробелы? типа `echo = abra`

2023-10-07 18:52 UTC, eqimd requested changes

2023-10-07 18:52 UTC, eqimd commented on internal/command/splitter/command_splitter_impl.go
>  func (splitter *CommandSplitterImpl) Split(s string) (command.Command, []command.CommandArgument, error) {
здесь еще наверное имеет смысл сначала сделать `s = strings.TrimSpace(s)`

2023-10-07 18:52 UTC, eqimd commented on internal/command/splitter/command_splitter_impl.go
> +	s = s + " "
вот тут убрать это добавление пробела, и после цикла просто сделать проверку
```go
if startFrom < len(s) {
    words = append(words, s[startFrom:])
}
```

2023-10-08 08:12 UTC, DenisKorotchenko commented on internal/command/splitter/gotest/command_splitter_test.go
> +	expectedArgs := make([]command.CommandArgument, 2)
потому что аргумент в кавычках

2023-10-08 08:23 UTC, DenisKorotchenko commented on internal/command/splitter/command_splitter_impl.go
>  func (splitter *CommandSplitterImpl) Split(s string) (command.Command, []command.CommandArgument, error) {
сделал другим способом

2023-10-08 08:26 UTC, DenisKorotchenko commented on internal/command/splitter/command_splitter_impl.go
> +	tryEnvSplit := strings.Split(commandWord, "=")
так нельзя. по спецификации (и я проверил на реально баше) создание новой переменной только без пробелов перед и после равно

2023-10-08 08:27 UTC, DenisKorotchenko commented on internal/command/splitter/command_splitter_impl.go
> +	s = s + " "
ну с проблеом то тоже работает и меньше кода)
я б оставил

2023-10-08 08:27 UTC, DenisKorotchenko commented on internal/command/splitter/command_splitter_impl.go
> +	var waitFor = rune(' ')
а чем руны плохи? вроде всё работает

2023-10-08 08:34 UTC, eqimd commented on internal/command/splitter/command_splitter_impl.go
> +	tryEnvSplit := strings.Split(commandWord, "=")
я имел ввиду, правильно ли команда echo в таком случае отработает

2023-10-08 08:35 UTC, eqimd commented on internal/command/splitter/command_splitter_impl.go
> +	var waitFor = rune(' ')
можно и оставить, в целом не критично

2023-10-08 08:35 UTC, eqimd commented on internal/command/splitter/command_splitter_impl.go
> +	s = s + " "
на твое усмотрение. главное чтоб тесты проходили и правильные были

2023-10-08 08:38 UTC, eqimd approved these changes

2023-10-08 08:38 UTC, eqimd commented on internal/command/splitter/gotest/command_splitter_test.go
> +	expectedArgs := make([]command.CommandArgument, 1)
можно просто `expectedArgs := []command.Command{args[0]}`
и в остальных тестах тоже

2023-10-10 11:57 UTC, merged